from . import prestashop_instance_integration
from . import product_listing
from . import product_listing_item
from . import product_pricelist
from . import res_partner
from . import sale_order
from . import ir_cron
from . import prestashop_log
from . import order_data_queue
from . import customer_data_queue
from . import inventory_data_queue
from . import product_attribute
from . import product_attribute_value
from . import product_data_queue
from . import product_category
