# -*- coding: utf-8 -*-pack
{  # App information
    'name': 'Odoo Prestashop Integration',
    'category': 'eCommerce',
    'version': '17.0.1.0',
    'summary': """
    """,
    'description': """ """,
    'depends': ['delivery', 'sale_stock', 'sale_management', 'account', 'stock_delivery'],
    'data': [
        'security/ir.model.access.csv',
        'wizard/prestashop_operation_view.xml',
        'data/order_status_data.xml',
        'data/cron.xml',
        'data/product_data.xml',
        'views/ir_cron.xml',
        'views/prestashop_log.xml',
        'views/product_category_view.xml',
        'views/product_attribute_value.xml',
        'views/order_data_queue.xml',
        'views/inventory_data_queue.xml',
        'views/customer_data_queue.xml',
        'views/prestashop_instance_integration.xml',
        'views/product_listing.xml',
        'views/product_listing_item.xml',
        'views/product_data_queue.xml',
        'views/res_partner.xml',
        'views/sale_order.xml',
        'views/menu_item.xml',
    ],

    # 'images': ['static/description/cover.gif'],
    'author': 'Vraja Technologies',
    'maintainer': 'Vraja Technologies',
    'website': 'https://www.vrajatechnologies.com',
    'live_test_url': 'https://www.vrajatechnologies.com/contactus',
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'OPL-1',
    'price': '',
    'currency': 'EUR',
}
